<template>
  <div class="agent-panel">
    <!-- 会话标签栏 -->
    <SessionTabs
      v-if="hasSessionTabs"
      :sessions="sessionStore.sessions"
      :activeId="sessionStore.activeSessionId"
      @select="sessionStore.setActiveSession($event)"
      @close="handleCloseSession($event)"
      @add="createNewSession"
    />

    <!-- 思考进度条 -->
    <div v-if="activeAgent?.isProcessing.value" class="thinking-progress">
      <div class="thinking-progress-bar"></div>
    </div>

    <!-- 引导页：无提供商 -->
    <div v-if="providerSettings.providers.value.length === 0" class="agent-guide">
      <div class="guide-icon"><n-icon size="36" :component="SettingsOutline" /></div>
      <div class="guide-title">{{ $t('agent.guideTitle') }}</div>
      <div class="guide-desc">
        {{ $t('agent.guideDesc1') }}<br />
        {{ $t('agent.guideDesc2') }}
      </div>
      <n-button type="primary" @click="showSettings = true">{{ $t('agent.addProvider') }}</n-button>
    </div>

    <!-- 引导页：无工作区 -->
    <div v-else-if="!editorStore.activeWorkspaceId && editorStore.workspaceRoots.length === 0" class="agent-guide">
      <div class="guide-icon"><n-icon size="36" :component="FolderOpenOutline" /></div>
      <div class="guide-title">{{ $t('agent.noWorkspaceTitle') }}</div>
      <div class="guide-desc">{{ $t('agent.noWorkspaceDesc') }}</div>
    </div>

    <!-- 引导页：无活跃会话 -->
    <div v-else-if="!activeAgent" class="agent-guide">
      <div class="guide-icon"><n-icon size="36" :component="AddOutline" /></div>
      <div class="guide-title">{{ $t('agent.noSessionPrompt') }}</div>
      <n-button type="primary" @click="createNewSession">{{ $t('agent.newSession') }}</n-button>
    </div>

    <!-- 正常聊天界面 -->
    <template v-else>
      <AgentChat
        ref="agentChatRef"
        :messages="activeAgent.messages.value"
        @undo-edits="emit('undo-edits')"
      />

      <ChatInput
        :isProcessing="activeAgent.isProcessing.value"
        :placeholder="$t('agent.askAgent')"
        @send="send"
        @stop="stopStream"
      />

      <div class="agent-footer">
        <div class="footer-left">
          <ProviderSelect
            :providers="providerSettings.providers.value"
            :activeId="providerSettings.activeId.value"
            @select="providerSettings.setActive($event)"
          />
          <n-button size="tiny" quaternary :title="$t('agent.providerSettings')" @click="showSettings = true">
            <template #icon><n-icon :component="SettingsOutline" /></template>
          </n-button>
        </div>
        <ModeSelector v-model="currentMode" />
      </div>
    </template>

    <!-- 设置对话框 -->
    <SettingsDialog :visible="showSettings" @close="showSettings = false" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, nextTick, onMounted } from 'vue';
import { NIcon, NButton } from 'naive-ui';
import { SettingsOutline, FolderOpenOutline, AddOutline } from '@vicons/ionicons5';
import { useSessionStore } from '../../stores/sessions';
import { useLLMSettings } from '../../composables/useLLMSettings';
import { useEditorStore } from '../../stores/editor';
import type { ParsedEdit } from '../../services/editParser';
import { webAgentLog } from '../../services/logger';
import SessionTabs from './SessionTabs.vue';
import AgentChat from './AgentChat.vue';
import ChatInput from './ChatInput.vue';
import SettingsDialog from './SettingsDialog.vue';
import ModeSelector from './ModeSelector.vue';
import ProviderSelect from './ProviderSelect.vue';

const emit = defineEmits<{
  'apply-edits': [edits: ParsedEdit[]];
  'undo-edits': [];
}>();

const sessionStore = useSessionStore();
const providerSettings = useLLMSettings();
const editorStore = useEditorStore();
const showSettings = ref(false);

const agentChatRef = ref<InstanceType<typeof AgentChat>>();
const activeAgent = computed(() => sessionStore.activeAgent);
const hasSessionTabs = computed(() => editorStore.activeWorkspaceId || providerSettings.providers.value.length > 0);

const currentMode = computed({
  get: () => activeAgent.value?.config.value.mode ?? 'plan',
  set: (val) => {
    if (activeAgent.value) {
      activeAgent.value.config.value.mode = val;
    }
  },
});

function createNewSession() {
  sessionStore.createSession();
}

function handleCloseSession(id: string) {
  sessionStore.closeSession(id);
}

async function send(text: string) {
  const agent = activeAgent.value;
  if (!agent) return;

  // 自动从首条消息命名会话
  if (sessionStore.activeSession && !sessionStore.activeSession.nameAutoGenerated) {
    sessionStore.autoNameFromFirstMessage(sessionStore.activeSession.id, text);
  }

  const activeFilePath = editorStore.activeTab?.path;

  webAgentLog.info('send: starting streamMessage');
  const streamPromise = agent.streamMessage(
    text,
    providerSettings.activeProvider.value,
    () => agentChatRef.value?.forceScrollBottom(),
    activeFilePath
  );

  agentChatRef.value?.forceScrollBottom();

  try {
    await streamPromise;
    webAgentLog.info('send: streamMessage completed');
  } catch (e: any) {
    webAgentLog.error(`send: streamMessage failed: ${e.message}`, { name: e.name, message: e.message });
  }

  sessionStore.saveCurrentSession();

  if (agent.lastEdits.value.length > 0) {
    emit('apply-edits', [...agent.lastEdits.value]);
    agent.lastEdits.value = [];
  }
}

function stopStream() {
  const agent = activeAgent.value;
  if (agent?.cancelStream) {
    agent.cancelStream();
  }
}

onMounted(() => {
  providerSettings.reload();
});
</script>

<style scoped>
.agent-panel {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: var(--bg-secondary);
  position: relative;
  overflow: hidden;
}

/* 思考进度条 */
.thinking-progress {
  position: absolute;
  top: 32px;
  left: 0;
  right: 0;
  height: 3px;
  z-index: 10;
  overflow: hidden;
  background: transparent;
}
.thinking-progress-bar {
  width: 40%;
  height: 100%;
  background: linear-gradient(90deg, transparent, var(--accent-color), transparent);
  animation: progress-scroll 1.2s ease-in-out infinite;
  border-radius: 2px;
}
@keyframes progress-scroll {
  0% { transform: translateX(-100%); }
  100% { transform: translateX(350%); }
}

/* Footer */
.agent-footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 6px 12px;
  border-top: 1px solid var(--border-color);
  gap: 8px;
  flex-shrink: 0;
}
.footer-left {
  display: flex;
  align-items: center;
  gap: 4px;
  min-width: 0;
}

/* 引导页 */
.agent-guide {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  padding: 32px 24px;
  user-select: none;
}
.guide-icon {
  font-size: 40px;
  color: var(--text-secondary);
  opacity: 0.35;
  margin-bottom: 14px;
}
.guide-title {
  font-size: 15px;
  font-weight: 600;
  margin-bottom: 6px;
}
.guide-desc {
  font-size: 12px;
  color: var(--text-secondary);
  margin-bottom: 22px;
  line-height: 1.5;
}
</style>
